CREATE USER taskmanager_user WITH PASSWORD 'taskmanager_pass';
CREATE DATABASE taskmanager_db OWNER taskmanager_user;
GRANT ALL PRIVILEGES ON DATABASE taskmanager_db TO taskmanager_user;

-- Table: public.users

-- DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
)

-- Table: public.tasks

-- DROP TABLE IF EXISTS public.tasks;

CREATE TABLE IF NOT EXISTS public.tasks
(
    task_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
    (
        INCREMENT 1
        START 1
        MINVALUE 1
        MAXVALUE 9223372036854775807
        CACHE 1
    ),
    task_status character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'todo',
    task_creation_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    start_date_time timestamp without time zone,
    end_date_time timestamp without time zone,
    task_title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    task_desc text COLLATE pg_catalog."default",
    created_by bigint NOT NULL,

    CONSTRAINT tasks_pkey PRIMARY KEY (task_id),
    CONSTRAINT tasks_created_by_fkey FOREIGN KEY (created_by)
        REFERENCES public.users (id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT tasks_task_status_check CHECK
    (
        task_status::text = ANY
        (
            ARRAY['todo'::character varying, 'in_progress'::character varying, 'done'::character varying]::text[]
        )
    )
);

